### ISSUE TITLE
Importing AsyncClient from nio is expensive

### ISSUE THREAD

**Issue by Redsandro** [tnyeanderson/sendmail-to-matrix#3]
Importing `AsyncClient` from `nio` is expensive. It would be interesting to find a way that keeps the script open and forward messages without re-importing AsyncClient for every message.

**Comment by tnyeanderson** [comment]
I'm gonna rewrite it in go. Statically linked binary with no dependencies solves these issues and more

**Comment by Redsandro** [comment]
I guess I can close this as "planned" then. :slightly_smiling_face:

**Comment by tnyeanderson** [comment]
Follow along in #4
